#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx

#Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Obafemitobi438 permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header

sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for Syntax errors
sudo nginx -t

#Restart nginx
sudo service nginx restart
